export enum ActionTypes {
  LOAD_USERS = "[Users] Load Users",
  LOAD_USERS_SUCCESS = "[Users] Load Users Success",
  LOAD_USERS_FAILURE = "[Users] Load Users Failure",
  ADD_USER = "[Users] Add User",
  ADD_USER_SUCCESS = "[Users] Add User Success",
  ADD_USER_FAILURE = "[Users] Add User Failure",
  DELETE_USER = "[Users] Delete User",
  DELETE_USER_SUCCESS = "[Users] Delete User Success",
  DELETE_USER_FAILURE = "[Users] Delete User Failure",
  DELETE_USERS = "[Users] Delete Users",
  DELETE_USERS_SUCCESS = "[Users] Delete Users Success",
  DELETE_USERS_FAILURE = "[Users] Delete Users Failure",
  EDIT_USERS = "[Users] Edit Users",
}
